#include("fixed/menu.sql")
#include("fixed/user.sql")
#include("fixed/post.sql")
#include("fixed/depart.sql")
#include("fixed/role.sql")
#include("fixed/jurisdiction.sql")
#include("fixed/base.sql")
#include("fixed/tableSetting.sql")